services:
  # --- Infrastructure ---
  postgres:
    image: postgres:16-alpine
    container_name: trace_db
    environment:
      POSTGRES_USER: trace_user
      POSTGRES_PASSWORD: trace_password
      POSTGRES_DB: trace_core
      JWT_SECRET: ${JWT_SECRET:-super-secret-dev-key-do-not-use-in-prod}
    ports:
      - "5432:5432"
    volumes:
      - trace_pg_data:/var/lib/postgresql/data
    networks:
      - trace_net

  redis:
    image: redis:7-alpine
    container_name: trace_cache
    ports:
      - "6379:6379"
    networks:
      - trace_net

  minio:
    image: minio/minio
    container_name: trace_blob
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - trace_blob_data:/data
    networks:
      - trace_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    container_name: trace_init_buckets
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set myminio http://minio:9000 minio_admin minio_password; do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb --ignore-existing --with-lock myminio/passports;
      exit 0;
      "
    networks:
      - trace_net

volumes:
  trace_pg_data:
  trace_blob_data:

networks:
  trace_net:
    name: trace_net
